задание 4
AntonNikol/otus-go pull request #4
Opened 2023-08-04 12:39 UTC by AntonNikol

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-08-05 05:41 UTC, vladislavmass requested changes
Хорошее начало. Круто что сделано удаление за O(1). К работе есть несколько замечаний поэтому принять пока немогу

2023-08-05 05:41 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		l.head = i.Next
Что будет если после этой операции обратится `l.head.Prev`

2023-08-05 05:41 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		l.tail = i.Prev
Что будет если после этой операции обратится `l.tail.Next`

2023-08-06 21:18 UTC, AntonNikol commented on hw04_lru_cache/list.go
> +		l.head = i.Next
Не понял вашего вопроса. 
Так как в первом условии я проверяю, находится ли элемент в голове списка 
```go if i.Prev != nil```  и если он все же находится в голове, то выполняется блок else в котором я определяю, что теперь головным элементом будет следующий после элемента i

2023-08-06 21:27 UTC, AntonNikol commented on hw04_lru_cache/list.go
> +		l.tail = i.Prev
Аналогичная ситуация происходит и тут, только с ссылкой на последний элемент. l.tail.Next всегда будет nil

2023-08-07 04:11 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		l.head = i.Next
Что произойдет когда выполнится ветка else. `l.head` станет равным элементу следующему за первым. Но при этом у этого элемента есть свои указатели на следующий и предыдущий элемент. И мы нигде не говорим этому следующему элементу о том, что теперь твой `Prev=nil`. И получается что в поле `Prev` все еще лежит указатель на удаленный элемент.

2023-08-07 09:20 UTC, AntonNikol commented on hw04_lru_cache/list.go
> +		l.head = i.Next
Вы правы, спасибо. Поправил немного функцию, чтобы проверка была без отрицания. Показалось, что так легче читается. Добавил удаление указателей

2023-08-07 09:22 UTC, AntonNikol commented on hw04_lru_cache/list.go
> +		l.head = i.Next
Спасибо, поправил. Также изменил на проверку в блоке if без отрицания. Показалось, что так код легче читается

2023-08-08 11:01 UTC, vladislavmass approved these changes
Отлично. Работа принята. 10/10

2023-08-08 21:12 UTC, vladislavmass requested changes
Нужен еще ряд правок

2023-08-08 21:12 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +func (l *list) MoveToFront(i *ListItem) {
Если мы последний элемент переместим в начало, то чему будет равен`l.tail`?

2023-08-09 07:53 UTC, AntonNikol commented
Поправил все указанные ошибки

> Нужен еще ряд правок

2023-08-09 08:44 UTC, vladislavmass requested changes
Данные исправления некорректны

2023-08-09 08:44 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	l.tail = i.Prev
Этот код должен срабатывать только если `i==l.tail`

2023-08-09 08:44 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		if i.Prev != nil {
это условие должно применяться к коду в 91 строчке

2023-08-09 08:44 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		if i.Next != nil {
это условие должно применяться к коду в 83 строчке

2023-08-09 10:38 UTC, AntonNikol commented on hw04_lru_cache/list.go
> +	l.tail = i.Prev
Действительно. Тут я изначально плохо подумал.

2023-08-09 10:39 UTC, AntonNikol commented on hw04_lru_cache/list.go
> +		if i.Prev != nil {
Но ведь оно и так применяется к 91 строке

2023-08-09 11:03 UTC, AntonNikol commented on hw04_lru_cache/list.go
> +		if i.Next != nil {
Можете объяснить почему? Не могу понять в чем ошибка в этой логике

```go // Если элемент первый в списке
	if i.Prev == nil {
		if i.Next != nil {
			l.head = i.Next
		}
		l.head.Prev = nil
	} else {
		i.Prev.Next = i.Next
	} ```

Я проверяю, если элемент первый в списке, то:
1) Проверяю есть ли следующий элемент, если да то новым первым элементом списка становится следующий элемент.
2) Для нового первого элемента списка обнуляю указать на предыдущий элемент

2023-08-10 06:36 UTC, vladislavmass requested changes

2023-08-10 06:36 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		if i.Prev != nil {
Да, ошибся. к 93 строке.

2023-08-10 06:36 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		if i.Next != nil {
Предположим что у нас в листе лежит всего 1 элемент и мы его удаляем.  У него Prev и Next равны nil. И мы получаем что этот элемент остается как head. Тоже самое будет и с tail и по факту мы элемент не удалили.

2023-08-14 07:14 UTC, merged