Hw07 file copying
AntonNikol/otus-go pull request #7
Opened 2023-08-27 20:18 UTC by AntonNikol

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-08-29 05:03 UTC, vladislavmass requested changes
Решение не работает.
![изображение](https://github.com/AntonNikol/otus-go/assets/74667007/19154236-9beb-49d4-8f30-904938321833)

 Темп файл создает в директории запуска, а не в директории назначения.
 Если при "переименование" произошла ошибка, то программа не убирает за собой temp файлы

2023-08-29 06:14 UTC, AntonNikol commented on hw07_file_copying/copy.go
> +	file, err := os.OpenFile(filePath, os.O_RDONLY, 0644) //nolint:gofumpt
Все верно. На локале поправил, закоммитить забыл. 
Каюсь 
Поправил. Прошу вернуть 1 бал =)

2023-08-29 06:20 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	file, err := os.OpenFile(filePath, os.O_RDONLY, 0644) //nolint:gofumpt
Хорошо) Бывает) Осталось заставить утилиту работать

2023-08-30 06:37 UTC, vladislavmass approved these changes
Вот теперь хорошая работа. Принято.

Из рекомендации могу сказать лишь то, что я не сторонник такого дробления. По сути в методы обернута вызов 1 функции и обработка ее ошибок.  Более интересным вариантом было бы сделать функцию `getFileForCopy` в которой было бы открытие файла, проверка его размеров. проверка что смещение не вылезает за размер файла. И вот этот метод открыл файл провалидировал файл и либо вернул файл, либо сказал что возникал вот такая ошибка.

Но это чисто дело вкуса

2023-09-14 10:05 UTC, merged